<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Domain\Executions\ExecutionAttemptStatus;
use App\Models\Artifact;
use App\Models\ExecutionAttempt;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

/**
 * @extends Factory<Artifact>
 */
final class ArtifactFactory extends Factory
{
    /**
     * Define one immutable simulated artifact reference.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'execution_attempt_id' => ExecutionAttempt::factory(),
            'artifact_type' => 'validation_result',
            'name' => 'Simulated validation result',
            'storage_disk' => null,
            'storage_path' => null,
            'external_reference' => sprintf(
                'simulation://artifacts/%s',
                Str::ulid(),
            ),
            'media_type' => 'application/json',
            'checksum_sha256' => hash(
                'sha256',
                (string) Str::uuid(),
            ),
            'byte_size' => 1024,
            'assumptions' => [
                'Validation output is generated by the simulation provider.',
            ],
            'confidence' => '0.9000',
            'evidence_still_required' => true,
            'actual_state' => 'unverified',
            'metadata' => [
                'scenario' => 'happy_path',
            ],
        ];
    }

    /**
     * Derive tenant and provider provenance from the selected attempt.
     */
    public function configure(): static
    {
        return $this->afterMaking(
            function (Artifact $artifact): void {
                /** @var ExecutionAttempt $attempt */
                $attempt = ExecutionAttempt::query()
                    ->with('execution')
                    ->findOrFail($artifact->execution_attempt_id);

                $artifact->forceFill([
                    'project_id' => $attempt->execution->project_id,
                    'execution_id' => $attempt->execution_id,
                    'execution_provider' => $attempt->execution_provider,
                    'simulation_mode' => $attempt->simulation_mode,
                    'simulation_seed' => $attempt->simulation_seed,
                ]);
            },
        );
    }

    /**
     * Bind the artifact to one explicit execution attempt.
     */
    public function forAttempt(ExecutionAttempt $attempt): static
    {
        return $this->state(fn (): array => [
            'project_id' => $attempt->execution->project_id,
            'execution_id' => $attempt->execution_id,
            'execution_attempt_id' => $attempt->id,
            'execution_provider' => $attempt->execution_provider,
            'simulation_mode' => $attempt->simulation_mode,
            'simulation_seed' => $attempt->simulation_seed,
        ]);
    }

    /**
     * Store the artifact in object storage instead of an external source.
     */
    public function stored(): static
    {
        return $this->state(fn (): array => [
            'storage_disk' => 'artifacts',
            'storage_path' => sprintf(
                'artifacts/%s.json',
                Str::ulid(),
            ),
            'external_reference' => null,
        ]);
    }

    /**
     * Create an artifact backed by a non-simulation provider attempt.
     */
    public function fromRealProvider(
        string $provider = 'github',
    ): static {
        $startedAt = now()->subSecond();

        return $this
            ->for(
                ExecutionAttempt::factory()->state([
                    'status' => ExecutionAttemptStatus::Completed,
                    'execution_provider' => $provider,
                    'model_identifier' => sprintf(
                        '%s-fixture',
                        $provider,
                    ),
                    'simulation_mode' => null,
                    'simulation_seed' => null,
                    'reported_state' => 'completed',
                    'observed_state' => 'artifact_recorded',
                    'actual_state' => 'observed',
                    'confidence' => '0.9500',
                    'started_at' => $startedAt,
                    'heartbeat_at' => now(),
                    'deadline_at' => $startedAt->addMinutes(15),
                    'finished_at' => now(),
                ]),
                'executionAttempt',
            )
            ->state(fn (): array => [
                'name' => 'Observed provider validation result',
                'external_reference' => sprintf(
                    '%s://artifacts/%s',
                    $provider,
                    Str::ulid(),
                ),
                'actual_state' => 'observed',
                'evidence_still_required' => true,
                'assumptions' => [],
                'metadata' => [
                    'fixture_provider' => $provider,
                ],
            ]);
    }
}
