import type { OrganizationSummary } from './organization';
import type { ProjectSetupConfiguration } from './project-setup';

/**
 * Persisted project configuration with its schema version.
 */
export type ProjectSettingsConfiguration = ProjectSetupConfiguration & {
    schemaVersion: number;
};

/**
 * One deterministic project configuration problem.
 */
export type ProjectConfigurationIssue = {
    key: string;
    step: string;
    message: string;
    remediation: string;
};

/**
 * Project-level completeness result returned by Laravel.
 */
export type ProjectConfigurationValidation = {
    complete: boolean;
    missingConfiguration: ProjectConfigurationIssue[];
};

/**
 * Safe credential metadata. Secret values are intentionally absent.
 */
export type ProjectCredentialMetadata = {
    configured: boolean;
    version: number | null;
    createdAt: string | null;
    rotatedAt: string | null;
};

/**
 * Safe Notion connection metadata returned by Laravel.
 */
export type ProjectIntegrationOverview = {
    provider: 'notion';
    status: 'connected' | 'failed' | null;
    workspaceId: string | null;
    workspaceName: string | null;
    databaseId: string | null;
    databaseName: string | null;
    lastFailureCode: string | null;
    lastTestedAt: string | null;
    lastConnectedAt: string | null;
    credential: ProjectCredentialMetadata;
};

/**
 * Server-authoritative permissions for configuration screens.
 */
export type ProjectConfigurationPermissions = {
    update: boolean;
    manageIntegrations: boolean;
};

/**
 * URLs generated by Laravel instead of reconstructed in React.
 */
export type ProjectConfigurationUrls = {
    project: string;
    settings: string;
    integrations: string;
    setup: string;
    setupSteps: Record<string, string>;
};

/**
 * Common props shared by settings and integration pages.
 */
export type ProjectConfigurationScreenProps = {
    organization: OrganizationSummary;
    project: {
        id: number;
        name: string;
        slug: string;
        archivedAt: string | null;
    };
    configuration: ProjectSettingsConfiguration | null;
    integration: ProjectIntegrationOverview;
    validation: ProjectConfigurationValidation;
    permissions: ProjectConfigurationPermissions;
    urls: ProjectConfigurationUrls;
};
