<?php

declare(strict_types=1);

namespace App\Http\Responses;

use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

final class RateLimitExceededResponse
{
    /**
     * Return a stable retry response for a rate-limited request.
     *
     * JSON clients receive the platform API error contract. Browser and
     * Inertia form submissions are redirected back with a validation-style
     * message so they remain inside the normal application experience.
     *
     * @param  array<string, string|int>  $headers
     */
    public static function make(
        Request $request,
        array $headers,
    ): JsonResponse|RedirectResponse {
        $retryAfterSeconds = self::retryAfterSeconds($headers);

        if ($request->expectsJson() && ! $request->header('X-Inertia')) {
            return ApiErrorResponse::make(
                request: $request,
                code: 'rate_limit_exceeded',
                message: 'Too many requests. Please retry later.',
                status: Response::HTTP_TOO_MANY_REQUESTS,
                retryable: true,
                details: [
                    'retry_after_seconds' => $retryAfterSeconds,
                ],
                retryAfterSeconds: $retryAfterSeconds,
            )->withHeaders($headers);
        }

        return back()
            ->withInput()
            ->withErrors([
                'rate_limit' => sprintf(
                    'Too many requests. Please retry in %d seconds.',
                    $retryAfterSeconds,
                ),
            ])
            ->withHeaders($headers);
    }

    /**
     * Read the retry delay generated by Laravel's throttle middleware.
     *
     * @param  array<string, string|int>  $headers
     */
    private static function retryAfterSeconds(array $headers): int
    {
        $retryAfter = $headers['Retry-After']
            ?? $headers['retry-after']
            ?? 60;

        return max(1, (int) $retryAfter);
    }
}
