<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Create organizations owned by the Identity module.
     */
    public function up(): void
    {
        Schema::create('organizations', function (Blueprint $table): void {
            // Table ownership: Identity module.
            $table->id();

            // Human-readable organization name.
            $table->string('name', 120);

            // Stable route-safe identifier generated by the application.
            $table->string('slug', 180)->unique();

            $table->timestamps();
        });
    }

    /**
     * Remove the organizations table.
     */
    public function down(): void
    {
        Schema::dropIfExists('organizations');
    }
};
