<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Create the durable transactional outbox used to publish domain events.
     */
    public function up(): void
    {
        Schema::create('outbox_messages', function (Blueprint $table): void {
            /*
             * A monotonic database sequence provides stable dispatcher ordering
             * without treating the domain event ULID as a database cursor.
             */
            $table->bigIncrements('sequence');

            /*
             * event_id is generated by DomainEventEnvelope and uniquely identifies
             * the logical event across transactions, retries, and consumers.
             */
            $table->ulid('event_id')->unique();

            $table->string('event_name', 191);
            $table->string('aggregate_type', 120);
            $table->string('aggregate_id', 191);

            /*
             * These are intentionally identifiers rather than foreign keys.
             *
             * An outbox message must remain publishable even when the originating
             * aggregate is archived or eventually removed by a separate lifecycle.
             */
            $table->unsignedBigInteger('organization_id');
            $table->unsignedBigInteger('project_id')->nullable();

            $table->timestampTz('occurred_at', precision: 6);

            $table->ulid('correlation_id');
            $table->ulid('causation_id')->nullable();
            $table->ulid('execution_id')->nullable();

            $table->unsignedInteger('schema_version');

            /*
             * Store the complete canonical AIOS-049 envelope. The dispatcher must
             * publish this exact representation rather than reconstructing it from
             * mutable domain or application state.
             */
            $table->jsonb('envelope');

            /*
             * AIOS-051 will set published_at after successful publication. No
             * attempt counters, leases, retry scheduling, or dead letters belong
             * to this ticket.
             */
            $table->timestampTz('published_at', precision: 6)->nullable();

            /*
             * created_at records outbox persistence time. occurred_at remains the
             * authoritative domain-event occurrence time.
             */
            $table
                ->timestampTz('created_at', precision: 6)
                ->useCurrent();

            /*
             * Supports ordered pending-message polling in AIOS-051.
             */
            $table->index(
                ['published_at', 'sequence'],
                'outbox_messages_pending_sequence_index',
            );

            /*
             * Supports tenant-scoped operational inspection and reconciliation.
             */
            $table->index(
                ['organization_id', 'project_id', 'sequence'],
                'outbox_messages_scope_sequence_index',
            );

            /*
             * Supports aggregate-history inspection without querying JSONB.
             */
            $table->index(
                ['aggregate_type', 'aggregate_id', 'sequence'],
                'outbox_messages_aggregate_sequence_index',
            );

            $table->index(
                'correlation_id',
                'outbox_messages_correlation_id_index',
            );
        });
    }

    /**
     * Remove the outbox table during an explicitly approved rollback.
     */
    public function down(): void
    {
        Schema::dropIfExists('outbox_messages');
    }
};
